name: Deploy to EC2

on:
  push:
    branches:
      - main # Ou outra branch que você deseja monitorar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add SSH key
        run: |
          echo "${{ secrets.EC2_PEM_KEY }}" > pem_file.pem
          chmod 600 pem_file.pem

      - name: Deploy to EC2
        run: |
          ssh -i pem_file.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /var/www/savina-store

            # Parar e remover o container Docker atual
            docker stop nextjs-app || true
            docker rm nextjs-app || true

            # Puxar as últimas alterações do repositório
            git pull origin main

            # Build da imagem Docker
            docker build -t nextjs-app .

            # Rodar o novo container Docker
            docker run -d -p 80:3000 --name nextjs-app nextjs-app

            docker system prune -af
          EOF
